---
- name: Deploy developers VM
  hosts: all
  become: yes

  vars:
    sysctl_settings:
      fs.file-max: 1000000
      fs.inotify.max_user_watches: 16777216
      kernel.core_uses_pid: 1
      kernel.msgmax: 8192
      kernel.msgmnb: 16384
      net.core.somaxconn: 65535
      net.core.netdev_max_backlog: 16384
      net.ipv4.ip_forward: 0
      net.ipv4.conf.all.accept_redirects: 1
      net.ipv4.conf.default.accept_redirects: 0
      net.ipv4.tcp_syncookies: 0
      net.ipv4.tcp_timestamps: 0

  tasks:

  - name: set sysctl settings
    sysctl: sysctl_set=yes reload=yes state=present
      name="{{ item.key }}"
      value="{{ item.value }}"
    with_dict: "{{ sysctl_settings }}"

  - name: Remove file APT
    ansible.builtin.file:
      path: /etc/apt/sources.list
      state: absent

  #- name: Run apt upgrade
  #  apt:
  #    upgrade: "yes"
  #    update_cache: yes
  #    cache_valid_time: 432000

  #- name: Add universe repository into sources list
  #  apt_repository:
  #    repo: deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe
  #    state: present

  - name: Install some system tools
    ansible.builtin.apt:
       name:
          - apt-transport-https
          - htop
          - mc
          - net-tools
          - libc6
          - libgcc1
          - libgssapi-krb5-2
          - libstdc++6
          - zlib1g
          - curl
          - wget
          - gnupg2
          - build-essential
       state: latest
       update_cache: true

#
# Libssl
#

  #- name: Download libssl
  #  ansible.builtin.get_url:
  #    url: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
  #    dest: /usr/src/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
  #    mode: '0440'

  #- name: Install libssl
  #  ansible.builtin.apt:
  #    deb: /usr/src/libssl1.1_1.1.0g-2ubuntu4_amd64.deb

  - name: Download Microsoft package repository
    get_url:
      url: "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
      dest: "/tmp/packages-microsoft-prod.deb"
      mode: '0644'
      #checksum: 'sha256:10cadd1e8b0136beae0336ce018b7e076335d9b3fb3c3fa3d4cf4b22c87fc4ca'

  - name: Install Microsoft package repository
    apt:
      deb: "/tmp/packages-microsoft-prod.deb"
      state: present

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install .NET 5 SDK
    apt:
      name: dotnet-sdk-5.0
      state: present

  - name: Install .NET 6 SDK
    apt:
      name: dotnet-sdk-6.0
      state: present

#  - name: Add NodeSoure repo
#    shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

#  - name: Update apt cache
#    apt:
#      update_cache=yes force_apt_get=yes cache_valid_time=3600

#  - name: Install Node
#    apt:
#      name: nodejs
#      update_cache: yes

#
# Install Dotnet
#

#  - name: Download packages-microsoft-prod
#    ansible.builtin.get_url:
#      url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
#      dest: /usr/src/packages-microsoft-prod.deb
#      mode: '0440'

#  - name: Install packages-microsoft-prod
#    ansible.builtin.apt:
#      deb: /usr/src/packages-microsoft-prod.deb
#      state: present
#      update_cache: true

#  - name: Install dotnet-sdk-5.0
#    shell: "apt -t focal install -y dotnet-sdk-5.0"
#
#  - name: Install dotnet-sdk-6.0
#    shell: "apt -t focal install -y dotnet-sdk-6.0"

  #- name: Install DotNet SDK 6.0
  #  ansible.builtin.apt:
  #     name:
  #        - dotnet-sdk-6.0
  #     state: latest
  #     update_cache: true

  #- name: Install dotnet-sdk 5.0
  #  snap:
  #     name: dotnet-sdk
  #     channel: 5.0
  #     classic: yes
  #     state: present

  #- name: Install dotnet-sdk-5.0
  #  ansible.builtin.apt:
  #     name:
  #        - dotnet-sdk-5.0
#
# Service config
#

  - name: Chmod o-x rsync
    ansible.builtin.file:
        path: /usr/bin/rsync
        owner: root
        group: root
        mode: '0644'

  - name: Replace sftp config
    ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '(^Subsystem sftp\s)(.*)$'
        replace: 'Subsystem sftp internal-sftp -P read, remove'

  - name: Restart sshd
    service:
        name: ssh
        state: restarted

  - name: Creating /etc/sysctl.d/fs.conf
    copy:
      dest: "/etc/sysctl.d/fs.conf"
      content: "fs.inotify.max_user_watches = 524288"

#
# User
#

  - name: Add a group Developer
    group:
        name: developer
        state: present

  - name: Add a user Developer
    user:
        name: developer
        password: $6$dZjGIVaxZmY7$lr8NX9BARnkklMWcgcXvZ4KHK7Oc4JHqxPAR./St7hEDv8lhwV7WtrguIfnJVwYsAh8jbj3K.xBu2GWGSxmX50
        shell: /bin/bash
        update_password: on_create
        groups: developer
        append: yes
        # mkpasswd --method=sha-512 LvHgB7l5XQ8K

  #- name: Make reboot for developer
    #copy:
      #dest: "/etc/sudoers.d/developer"
      #content: ""
      #content: "developer ALL=NOPASSWD: /sbin/reboot"


  #- name: Request for change password
  #  shell:
  #        "chage --lastday 0 developer"

#  shell:

  #- name: Create a directory /bin
  #  file:
  #      path: /home/developer/bin
  #      state: directory
  #      mode: '0755'


  #- name: Copy .bash_profile to home folder
  #  shell:
  #        "cp /usr/src/gp-deploy-developers-vm/.bash_profile /home/developer/.bash_profile"
