---
- name: Deploy developers VM
  hosts: all
  become: yes

  tasks:

  - name: Install some system tools
    ansible.builtin.apt:
       name:
          - htop
          - mc
          - net-tools
          - busybox
       state: latest
       update_cache: true

  - name: Install DotNetCore 5.0
    ansible.builtin.snap:
       name: dotnet-sdk
       channel: 5.0
       classic: yes
       state: present

  - name: Replace sftp config
    ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '(^Subsystem sftp\s)(.*)$'
        replace: 'Subsystem sftp internal-sftp -P read, remove'

  - name: Restart sshd
    service:
        name: ssh
        state: restarted

  - name: Clone GP from github
    ansible.builtin.git:
        repo: 'https://github.com/rmtteam/gp-deploy-developers-vm.git'
        dest: /usr/src/gp-deploy-developers-vm

  - name: Add a group Developer
    group:
        name: developer
        state: present

  - name: Add a user Developer
    user:
        name: developer
        password: $6$dZjGIVaxZmY7$lr8NX9BARnkklMWcgcXvZ4KHK7Oc4JHqxPAR./St7hEDv8lhwV7WtrguIfnJVwYsAh8jbj3K.xBu2GWGSxmX50
        shell: /bin/bash
        update_password: on_create
        groups: developer
        append: yes
        # mkpasswd --method=sha-512 LvHgB7l5XQ8K




#  - name: Create a symbolic link to git
#    file:
#        src: /usr/bin/git
#        dest: /home/developer/bin/git
#        owner: developer
#        group: developer
#        state: link
