---
- name: Deploy developers VM
  hosts: all
  become: yes

  tasks:

  #- name: Run apt upgrade
  #  apt:
  #    upgrade: "yes"
  #    update_cache: yes
  #    cache_valid_time: 432000

  - name: Install some system tools
    ansible.builtin.apt:
       name:
          - htop
          - mc
          - net-tools
       state: latest
       update_cache: true

  - name: Install DotNetCore 5.0
    ansible.builtin.snap:
       name: dotnet-sdk
       channel: 5.0
       classic: yes
       state: present

  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
      path: /usr/bin/rsync
      mode: o-x

  - name: Replace sftp config
    ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '(^Subsystem sftp\s)(.*)$'
        replace: 'Subsystem sftp internal-sftp -P read, remove'

  - name: Restart sshd
    service:
        name: ssh
        state: restarted

  - name: Clone GP from github
    ansible.builtin.git:
        repo: 'https://github.com/rmtteam/gp-deploy-developers-vm.git'
        dest: /usr/src/gp-deploy-developers-vm

  - name: Remove playbook-deploy-developers-vm.yml
    ansible.builtin.file:
        path: /usr/src/gp-deploy-developers-vm/playbook-deploy-developers-vm.yml
        state: absent

  - name: Add a group Developer
    group:
        name: developer
        state: present

  - name: Add a user Developer
    user:
        name: developer
        password: $6$dZjGIVaxZmY7$lr8NX9BARnkklMWcgcXvZ4KHK7Oc4JHqxPAR./St7hEDv8lhwV7WtrguIfnJVwYsAh8jbj3K.xBu2GWGSxmX50
        shell: /bin/bash
        update_password: on_create
        groups: developer
        append: yes
        # mkpasswd --method=sha-512 LvHgB7l5XQ8K

  - name: Create a directory /bin
    file:
        path: /home/developer/bin
        state: directory
        mode: '0755'

  #- name: Copy .bash_profile to home folder
  #  shell:
  #        "cp /usr/src/gp-deploy-developers-vm/.bash_profile /home/developer/.bash_profile"

  - name: Create a symbolic link to git
    file:
        src: /usr/bin/git
        dest: /home/developer/bin/git
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to uname
    file:
        src: /usr/bin/uname
        dest: /home/developer/bin/uname
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to echo
    file:
        src: /usr/bin/echo
        dest: /home/developer/bin/echo
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to rbash
    file:
        src: /usr/bin/rbash
        dest: /home/developer/bin/rbash
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to lesspipe
    file:
        src: /usr/bin/lesspipe
        dest: /home/developer/bin/lesspipe
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to dircolors
    file:
        src: /usr/bin/dircolors
        dest: /home/developer/bin/dircolors
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to groups
    file:
        src: /usr/bin/groups
        dest: /home/developer/bin/groups
        owner: developer
        group: developer
        state: link

  - name: Create a symbolic link to mc
    file:
        src: /usr/bin/mc
        dest: /home/developer/bin/mc
        owner: developer
        group: developer
        state: link
